import 'package:flutter_test/flutter_test.dart';
import 'package:arcadiaplus/src/services/system_dns_service.dart';

void main() {
  group('resolv.conf parsing', () {
    test('keeps nameserver lines in order and nothing else', () {
      const contents = '''
# Generated by NetworkManager
search lan
nameserver 192.168.1.1
nameserver 2001:4860:4860::8888   # Google
options edns0 trust-ad
nameserver
''';

      expect(SystemDnsService.parseResolvConf(contents), [
        '192.168.1.1',
        '2001:4860:4860::8888',
      ]);
    });

    test('a directive that merely starts with the word is not one', () {
      expect(SystemDnsService.parseResolvConf('nameservers 1.1.1.1'), isEmpty);
    });
  });

  group('Windows registry parsing', () {
    test(
      'reads both the static and the DHCP value, comma or space separated',
      () {
        const output = r'''
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{aaa}
    DhcpNameServer    REG_SZ    192.168.1.1,192.168.1.2
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{bbb}
    NameServer    REG_SZ    9.9.9.9 149.112.112.112
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{bbb}
    DhcpIPAddress    REG_SZ    192.168.1.10
''';

        expect(SystemDnsService.parseWindowsRegistry(output), [
          '192.168.1.1',
          '192.168.1.2',
          '9.9.9.9',
          '149.112.112.112',
        ]);
      },
    );

    test('an interface with no servers contributes nothing', () {
      expect(SystemDnsService.parseWindowsRegistry(''), isEmpty);
    });
  });

  group('sanitising', () {
    test(
      'drops what the engine cannot use, keeps order, removes duplicates',
      () {
        final servers = SystemDnsService.sanitise([
          '1.1.1.1',
          'dns.example.com', // needs the resolver it would be part of
          '1.1.1.1', // duplicate
          '127.0.0.53', // the stub that may be us
          '223.5.5.5',
          ' ::1 ',
          '',
          'fe80::1',
        ]);

        expect(servers, ['1.1.1.1', '223.5.5.5', 'fe80::1']);
      },
    );
  });
}
