// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `run`

/// Point the engine's GeoIP matcher at a database file on disk.
///
/// corduit resolves `Country.mmdb` from `CORDUIT_GEOIP_DB`, or next to the
/// running executable. Neither applies to a Flutter app: the asset bundle is
/// sealed inside the APK / `.app` / install directory. The Dart side unpacks
/// the bundled database to a real path and registers it here, which must
/// happen before [`initialize_corduit`] — that call is where the router
/// builds its matcher, and `GEOIP` rules stay inert without a database.
///
/// A missing file is reported instead of silently leaving `GEOIP` rules
/// unmatched, so a broken deployment cannot pass for a working one.
Future<void> setGeoipDatabasePath({required String path}) =>
    RustLib.instance.api.crateApiSetGeoipDatabasePath(path: path);

/// Validate a config without starting anything.
Future<bool> testConfig({required String configJson}) =>
    RustLib.instance.api.crateApiTestConfig(configJson: configJson);

/// Build the engine from a JSON config. Does not start listeners.
Future<void> initializeCorduit({required String configJson}) =>
    RustLib.instance.api.crateApiInitializeCorduit(configJson: configJson);

/// Start listeners, outbounds and the DNS server.
Future<void> startCorduit() => RustLib.instance.api.crateApiStartCorduit();

/// Stop the engine and release every listener it owns.
Future<void> stopCorduit() => RustLib.instance.api.crateApiStopCorduit();

/// Replace the running config.
Future<void> reloadCorduit({required String configJson}) =>
    RustLib.instance.api.crateApiReloadCorduit(configJson: configJson);

/// Engine status snapshot.
Future<ProxyStatus> getCorduitStatus() =>
    RustLib.instance.api.crateApiGetCorduitStatus();

/// Start the engine straight from a config document.
///
/// The name keeps corduit's spelling; the engine parses **JSON** in the
/// `CorduitConfig` shape (`outbound_type`/`inbound_type`/`rule_type` plus a
/// JSON `options` string), not YAML.
Future<void> startProxyFromYaml({required String yamlConfig}) =>
    RustLib.instance.api.crateApiStartProxyFromYaml(yamlConfig: yamlConfig);

/// Start the engine from a config file holding the same JSON document.
Future<void> startProxyFromFile({required String configPath}) =>
    RustLib.instance.api.crateApiStartProxyFromFile(configPath: configPath);

Future<void> stopProxy() => RustLib.instance.api.crateApiStopProxy();

Future<bool> isProxyRunning() => RustLib.instance.api.crateApiIsProxyRunning();

/// Replace the running config from a config document (JSON, same shape as
/// [`start_proxy_from_yaml`]).
Future<void> reloadConfigFromYaml({required String yamlConfig}) =>
    RustLib.instance.api.crateApiReloadConfigFromYaml(yamlConfig: yamlConfig);

/// Replace the running config from a JSON config file on disk.
Future<void> reloadConfigFromFile({required String configPath}) =>
    RustLib.instance.api.crateApiReloadConfigFromFile(configPath: configPath);

Future<void> setProxyMode({required int mode}) =>
    RustLib.instance.api.crateApiSetProxyMode(mode: mode);

Future<int> getProxyMode() => RustLib.instance.api.crateApiGetProxyMode();

Future<List<ProxyInfoDto>> getProxies() =>
    RustLib.instance.api.crateApiGetProxies();

Future<List<ProxyGroupDto>> getProxyGroups() =>
    RustLib.instance.api.crateApiGetProxyGroups();

Future<void> selectProxy({
  required String groupTag,
  required String proxyTag,
}) => RustLib.instance.api.crateApiSelectProxy(
  groupTag: groupTag,
  proxyTag: proxyTag,
);

Future<bool> selectProxyInGroup({
  required String groupName,
  required String proxyName,
}) => RustLib.instance.api.crateApiSelectProxyInGroup(
  groupName: groupName,
  proxyName: proxyName,
);

Future<String?> getSelectedProxyInGroup({required String groupName}) =>
    RustLib.instance.api.crateApiGetSelectedProxyInGroup(groupName: groupName);

/// Round-trip to `test_url` through the named outbound; returns millis.
Future<BigInt> testProxyLatencyDto({
  required String tag,
  required String testUrl,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiTestProxyLatencyDto(
  tag: tag,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
);

Future<List<ProxyLatencyDto>> testAllProxiesLatency({
  required String testUrl,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiTestAllProxiesLatency(
  testUrl: testUrl,
  timeoutMs: timeoutMs,
);

Future<LatencyTestResult> testProxyLatency({
  required String server,
  required int port,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiTestProxyLatency(
  server: server,
  port: port,
  timeoutMs: timeoutMs,
);

Future<LatencyTestResult> testOutboundLatency({
  required String outboundName,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiTestOutboundLatency(
  outboundName: outboundName,
  timeoutMs: timeoutMs,
);

Future<LatencyTestResult> testTcpConnectivity({
  required String server,
  required int port,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiTestTcpConnectivity(
  server: server,
  port: port,
  timeoutMs: timeoutMs,
);

Future<LatencyTestResult> testShadowsocksLatency({
  required String server,
  required int port,
  required String password,
  required String cipher,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiTestShadowsocksLatency(
  server: server,
  port: port,
  password: password,
  cipher: cipher,
  timeoutMs: timeoutMs,
);

Future<List<LatencyTestResult>> testProxiesLatency({
  required List<(String, int)> proxies,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiTestProxiesLatency(
  proxies: proxies,
  timeoutMs: timeoutMs,
);

Future<TrafficStats> getTrafficStats() =>
    RustLib.instance.api.crateApiGetTrafficStats();

Future<TrafficStatsDto> getTrafficStatsDto() =>
    RustLib.instance.api.crateApiGetTrafficStatsDto();

Future<List<ConnectionInfo>> getConnections() =>
    RustLib.instance.api.crateApiGetConnections();

Future<List<ConnectionDto>> getConnectionsDto() =>
    RustLib.instance.api.crateApiGetConnectionsDto();

Future<List<ActiveConnection>> getActiveConnections() =>
    RustLib.instance.api.crateApiGetActiveConnections();

Future<void> closeConnection({required String connectionId}) =>
    RustLib.instance.api.crateApiCloseConnection(connectionId: connectionId);

Future<void> closeConnectionById({required String id}) =>
    RustLib.instance.api.crateApiCloseConnectionById(id: id);

Future<bool> closeActiveConnection({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiCloseActiveConnection(connectionId: connectionId);

Future<void> closeAllConnections() =>
    RustLib.instance.api.crateApiCloseAllConnections();

Future<void> closeAllConnectionsDto() =>
    RustLib.instance.api.crateApiCloseAllConnectionsDto();

/// Counters as `(total_count, total_upload, total_download, active_count)`.
Future<(BigInt, BigInt, BigInt, BigInt)> getConnectionStats() =>
    RustLib.instance.api.crateApiGetConnectionStats();

Future<List<RuleDto>> getRules() => RustLib.instance.api.crateApiGetRules();

Future<DnsConfigDto> getDnsConfig() =>
    RustLib.instance.api.crateApiGetDnsConfig();

/// Start VeloGuard's recursive resolver front-end (RecurseX).
///
/// `listen` is a `host:port` pair; port `0` asks the OS for a free port
/// and the bound address is returned. Queries are answered by iterative
/// resolution from the root — no upstream forwarder is involved.
///
/// Calling this while an instance is already running returns the existing
/// address instead of rebinding.
Future<String> startRecursiveDns({required String listen}) =>
    RustLib.instance.api.crateApiStartRecursiveDns(listen: listen);

/// Stop the recursive resolver front-end.
Future<void> stopRecursiveDns() =>
    RustLib.instance.api.crateApiStopRecursiveDns();

Future<RecursiveDnsStatus> getRecursiveDnsStatus() =>
    RustLib.instance.api.crateApiGetRecursiveDnsStatus();

Future<List<String>> getLogs({int? lines}) =>
    RustLib.instance.api.crateApiGetLogs(lines: lines);

Future<void> setLogLevel({required String level}) =>
    RustLib.instance.api.crateApiSetLogLevel(level: level);

Future<SystemInfo> getSystemInfo() =>
    RustLib.instance.api.crateApiGetSystemInfo();

Future<String> getVersion() => RustLib.instance.api.crateApiGetVersion();

Future<String> getBuildInfo() => RustLib.instance.api.crateApiGetBuildInfo();

Future<void> startTunMode({
  required String tunName,
  required String tunAddress,
  required String tunNetmask,
}) => RustLib.instance.api.crateApiStartTunMode(
  tunName: tunName,
  tunAddress: tunAddress,
  tunNetmask: tunNetmask,
);

Future<void> stopTunMode() => RustLib.instance.api.crateApiStopTunMode();

Future<TunStatus> enableTunMode() =>
    RustLib.instance.api.crateApiEnableTunMode();

Future<TunStatus> enableTunModeWithMode({required String mode}) =>
    RustLib.instance.api.crateApiEnableTunModeWithMode(mode: mode);

Future<TunStatus> disableTunMode() =>
    RustLib.instance.api.crateApiDisableTunMode();

Future<TunStatus> getTunStatus() => RustLib.instance.api.crateApiGetTunStatus();

Future<void> setVpnFd({required int fd}) =>
    RustLib.instance.api.crateApiSetVpnFd(fd: fd);

Future<void> clearVpnFd() => RustLib.instance.api.crateApiClearVpnFd();

Future<void> setProtectSocketCallbackEnabled({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiSetProtectSocketCallbackEnabled(enabled: enabled);

Future<bool> isWintunAvailable() =>
    RustLib.instance.api.crateApiIsWintunAvailable();

Future<String?> getWintunDllPath() =>
    RustLib.instance.api.crateApiGetWintunDllPath();

Future<String> ensureWintunDll() =>
    RustLib.instance.api.crateApiEnsureWintunDll();

Future<bool> enableUwpLoopback() =>
    RustLib.instance.api.crateApiEnableUwpLoopback();

Future<bool> openUwpLoopbackUtility() =>
    RustLib.instance.api.crateApiOpenUwpLoopbackUtility();

Future<bool> setWindowsProxyMode({required String mode}) =>
    RustLib.instance.api.crateApiSetWindowsProxyMode(mode: mode);

Future<String> getWindowsProxyModeStr() =>
    RustLib.instance.api.crateApiGetWindowsProxyModeStr();

/// Windows TUN counters as `(packets_received, packets_sent, bytes_received,
/// bytes_sent, tcp_connections, udp_sessions)`.
Future<(BigInt, BigInt, BigInt, BigInt, BigInt, BigInt)> getWindowsTunStats() =>
    RustLib.instance.api.crateApiGetWindowsTunStats();

Future<void> setAndroidVpnFd({required int fd}) =>
    RustLib.instance.api.crateApiSetAndroidVpnFd(fd: fd);

Future<int> getAndroidVpnFd() => RustLib.instance.api.crateApiGetAndroidVpnFd();

Future<void> clearAndroidVpnFd() =>
    RustLib.instance.api.crateApiClearAndroidVpnFd();

Future<void> setAndroidProxyMode({required String mode}) =>
    RustLib.instance.api.crateApiSetAndroidProxyMode(mode: mode);

Future<String> getAndroidProxyMode() =>
    RustLib.instance.api.crateApiGetAndroidProxyMode();

Future<bool> startAndroidVpn() =>
    RustLib.instance.api.crateApiStartAndroidVpn();

Future<bool> stopAndroidVpn() => RustLib.instance.api.crateApiStopAndroidVpn();
