// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Traffic statistics
///
/// Not part of the FFI surface: the Dart-facing DTO with the same name lives in
/// `crate::types`. Two identically named types in one crate make the bridge's
/// code generator pick one at random (its own log says so), which is why the
/// FFI surface keeps the DTO and this internal accumulator stays internal.
class TrafficStats {
  /// Bytes uploaded
  final BigInt uploadBytes;

  /// Bytes downloaded
  final BigInt downloadBytes;

  /// Number of connections
  final BigInt connections;

  /// Total connection time in seconds
  final BigInt connectionTimeSecs;

  const TrafficStats({
    required this.uploadBytes,
    required this.downloadBytes,
    required this.connections,
    required this.connectionTimeSecs,
  });

  @override
  int get hashCode =>
      uploadBytes.hashCode ^
      downloadBytes.hashCode ^
      connections.hashCode ^
      connectionTimeSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafficStats &&
          runtimeType == other.runtimeType &&
          uploadBytes == other.uploadBytes &&
          downloadBytes == other.downloadBytes &&
          connections == other.connections &&
          connectionTimeSecs == other.connectionTimeSecs;
}
